pragma Singleton

import QtQuick

QtObject {
    readonly property color transparent: "transparent"
    readonly property color background: "#F5F7FB"
    readonly property color panel: "#FFFFFF"
    readonly property color panelTint: "#EEF6FF"
    readonly property color border: "#D7E2F0"
    readonly property color text: "#172033"
    readonly property color muted: "#64748B"
    readonly property color blue: "#2563EB"
    readonly property color blueHover: "#1D4ED8"
    readonly property color red: "#DC2626"
    readonly property color redHover: "#B91C1C"
    readonly property color softAction: "#F1F5F9"
    readonly property color softActionHover: "#E2E8F0"
    readonly property color comboBorder: "#BFDBFE"
    readonly property color comboButton: "#DBEAFE"
    readonly property color comboHover: "#EFF6FF"
    readonly property color comboSelected: "#EAF2FF"
    readonly property color strongText: "#0F172A"
    readonly property color secondaryText: "#475569"
    readonly property color controlText: "#334155"
    readonly property color titleMenuCurrentSurface: "#AAB7C8"
    readonly property color titleMenuCurrentText: "#1E293B"
    readonly property color titleMenuHover: "#D5DFED"
    readonly property color appWindowControlHover: "#CBD5E1"
    readonly property color infoText: "#1E3A8A"
    readonly property color infoBorder: "#93C5FD"
    readonly property color subtleSurface: "#F8FAFC"
    readonly property color divider: "#E5E7EB"
    readonly property color sidePanel: "#FCFDFF"
    readonly property color sidePanelBorder: "#D9E1EC"
    readonly property color toolUsageSurface: "#F1F7FF"
    readonly property color toolUsageBorder: "#D0E3FA"
    readonly property color summaryBorder: "#D8E0EC"
    readonly property color success: "#047857"
    readonly property color successAction: "#16A34A"
    readonly property color successHeading: "#15803D"
    readonly property color successText: "#166534"
    readonly property color successSurface: "#DCFCE7"
    readonly property color successDoneSurface: "#ECFDF5"
    readonly property color successHover: "#BBF7D0"
    readonly property color successBorder: "#86EFAC"
    readonly property color warningStrong: "#B45309"
    readonly property color warningText: "#92400E"
    readonly property color warningSurface: "#FEF3C7"
    readonly property color warningHover: "#FDE68A"
    readonly property color warningBorder: "#FCD34D"
    readonly property color warningStrongBorder: "#F59E0B"
    readonly property color reviewSurface: "#FFF7ED"
    readonly property color reviewText: "#9A3412"
    readonly property color reviewHover: "#FFEDD5"
    readonly property color dangerStrong: "#B42318"
    readonly property color dangerFill: "#D92D20"
    readonly property color dangerDisabled: "#F2B8B5"
    readonly property color dangerSurface: "#FEF2F2"
    readonly property color dangerBorder: "#FECACA"
    readonly property color todoSurface: "#FFF1F2"
    readonly property color todoText: "#991B1B"
    readonly property color monthlyText: "#3730A3"
    readonly property color monthlySurface: "#EEF2FF"
    readonly property color monthlyHover: "#E0E7FF"
    readonly property color monthlyBorder: "#C7D2FE"
    readonly property color taskBorder: "#E2E8F0"
    readonly property color taskReadySurface: "#D1D5DB"
    readonly property color taskReadyText: "#111827"
    readonly property color taskTriggeredSurface: "#D1FAE5"
    readonly property color neutralActionHover: "#CBD5E1"
    readonly property color strongHeader: "#123B65"
    readonly property color strongHeaderStatus: "#BFDBFE"
    readonly property int noRadius: 0
    readonly property int borderWidth: 1
    readonly property int focusBorderWidth: 2
    readonly property int noBorderWidth: 0
    readonly property int maximumWindowExtent: 16777215
    readonly property int radiusSmall: 4
    readonly property int radius: 8
    readonly property int radiusTab: 9
    readonly property int radiusMedium: 10
    readonly property int radiusLarge: 12
    readonly property int radiusSheet: 14
    readonly property int radiusPanel: 16
    readonly property int captionSize: 12
    readonly property int bodySize: 13
    readonly property int labelSize: 14
    readonly property int controlSize: 15
    readonly property int sectionTitleSize: 16
    readonly property int windowTitleSize: 17
    readonly property int subtitleSize: 18
    readonly property int panelTitleSize: 19
    readonly property int heroTitleSize: 24
    readonly property int displaySize: 31
    readonly property int appTitleBarHeight: 32
    readonly property int appWindowControlWidth: 40
    readonly property int appWindowControlIconSize: 18
    readonly property int appWindowControlSymbolSize: 12
    readonly property int appWindowControlSymbolStrokeWidth: 1
    readonly property int appWindowControlSymbolRadius: 1
    readonly property int appTitleMenuButtonWidth: 48
    readonly property int appTitleMenuButtonHeight: 28
    readonly property int appTitleMenuSpacing: 1
    readonly property int appContentTopSpacing: 2
    readonly property int appContentBottomSpacing: 14
    readonly property int appResizeHandleWidth: 6
    readonly property int dutyTaskRowHeight: 44
    readonly property int auditTaskRowHeight: 34
    readonly property int dutyTaskGridInset: 4
    readonly property int dutyTaskTimeWidth: 82
    readonly property int dutyTaskSystemWidth: 54
    readonly property int dutyTaskPeopleWidth: 84
    readonly property int taskStatusWidth: 96
    readonly property int taskStatusHeight: 28
    readonly property int auditTaskComparisonWidth: 104
    readonly property int auditTaskTimeWidth: 82
    readonly property int auditTaskActorWidth: 70
    readonly property int auditTaskTargetWidth: 100
    readonly property int auditTaskSystemWidth: 70
    readonly property int dutyModeButtonWidth: 112
    readonly property int dutyActionButtonWidth: 104
    readonly property int dutyActionButtonHeight: 38
    readonly property int settingsButtonSize: 34
    readonly property int settingsIconSize: 16
    readonly property int settingsIconRingSize: 10
    readonly property int settingsIconSpokeWidth: 2
    readonly property int settingsIconSpokeHeight: 4
    readonly property int toolDateFieldWidth: 112
    readonly property int toolDateStepWidth: 32
    readonly property int auditRefreshButtonWidth: 88
    readonly property int calendarPopupWidth: 292
    readonly property int calendarDayHeight: 30
    readonly property int toolBrowseButtonWidth: 64
    readonly property int toolBrowseButtonHeight: 30
    readonly property int monthlySourceOpenButtonWidth: 112
    readonly property int toolCompactControlHeight: toolBrowseButtonHeight
    readonly property int toolDateStepHeight: toolCompactControlHeight
    readonly property int toolMonthComboWidth: 78
    readonly property int toolMonthComboHeight: toolCompactControlHeight
    readonly property int toolUsageHeaderHeight: 28
    readonly property int toolUsageRowHeight: 30
    readonly property int toolUsageMaxHeight: 104
    readonly property int toolFieldLabelWidth: 50
    readonly property int toolUsageCardRowHeight: 24
    readonly property int toolUsageTimeWidth: 112
    readonly property int toolUsageResultWidth: 54
    readonly property int toolSectionMarkerWidth: 4
    readonly property int toolSectionMarkerHeight: 20
    readonly property int toolSectionDividerHeight: 2
    readonly property int comboArrowWidth: 10
    readonly property int comboArrowHeight: 6
    readonly property int comboArrowInset: 1
    readonly property int comboArrowStrokeWidth: 1
    readonly property int toolCloseButtonWidth: 90
    readonly property int toolSmallButtonHeight: 32
    readonly property int toolActionButtonHeight: 38
    readonly property int toolRunButtonHeight: 50
    readonly property int toolStatusHeight: 40
    readonly property int toolBackIconSize: 24
    readonly property color sideStatusReadySurface: "#F2F2F7"
    readonly property color sideStatusReadyBorder: "#D1D1D6"
    readonly property color sideStatusReadyText: "#636366"
    readonly property color sideStatusProgressSurface: "#F0F7FF"
    readonly property color sideStatusProgressBorder: "#B8D8FF"
    readonly property color sideStatusProgressText: "#007AFF"
    readonly property color sideStatusSuccessSurface: "#F0FAF2"
    readonly property color sideStatusSuccessBorder: "#BFE8C8"
    readonly property color sideStatusSuccessText: "#248A3D"
    readonly property color sideStatusWarningSurface: "#FFF8E5"
    readonly property color sideStatusWarningBorder: "#F2D27A"
    readonly property color sideStatusWarningText: "#8A5A00"
    readonly property color sideStatusErrorSurface: "#FFF2F1"
    readonly property color sideStatusErrorBorder: "#FFC9C5"
    readonly property color sideStatusErrorText: "#C62828"
    readonly property int workLogValueFieldWidth: 34
    readonly property int workLogValueFieldHeight: 28
    readonly property int workLogRestoreButtonWidth: 104
    readonly property int workLogActionButtonWidth: 86
    readonly property int buttonFeedbackDuration: 100
    readonly property int buttonColorTransitionDuration: 120
    readonly property int sidePanelTransitionDuration: 140
    readonly property int rescueWindowWidth: 1100
    readonly property int rescueWindowHeight: 720
    readonly property int rescueWindowMinimumWidth: 980
    readonly property int rescueWindowMinimumHeight: 560
    readonly property int rescueHeaderHeight: 58
    readonly property int rescueVehicleWidth: 140
    readonly property int rescueDateWidth: 150
    readonly property int rescueCheckMarkerRadius: 2
    readonly property int rescueResultRowHeight: 38
    readonly property int dataSourceWidth: 145
    readonly property int dataTimeWidth: 120
    readonly property int dataCaseWidth: 145
    readonly property int dataStatusWidth: 110
    readonly property int dataDestinationWidth: 210
    readonly property int dataNoteWidth: 180
}
